### PR TITLE
Fix #31 Force codeql analysis to use internal repos

### LINKED ISSUE #31: Force codeql analysis to use internal repos

### PR DESCRIPTION
**Pull request by jandusil**
- Add JAVA_TOOL_OPTIONS for the codeql autobuild

### CODE REVIEW

**Comment by jandusil** [comment]
Seems to be working properly, please see https://github.com/wultra/enrollment-server/actions/runs/5798127228/job/15715191882 for example

**Review by banterCZ — APPROVED** [review]
Looks good.

**Comment by jandusil** [comment]
Please check the run of the reviewed codeql parent

https://github.com/wultra/enrollment-server/actions/runs/5867402985

**Comment by jandusil** [comment]
Regarding this PR there must be changes made in several other repos and their codeql-analysis scripts respectively

- [ ] enrollment-server [PR](https://github.com/wultra/enrollment-server/pull/833)
- [ ] powerauth-server [PR](https://github.com/wultra/powerauth-server/pull/967)
- [ ] lime-core-java [PR](https://github.com/wultra/lime-java-core/pull/205)

**Review by zcgandcomp — APPROVED** [review]
Secrets are propagated and `JAVA_TOOL_OPTIONS` seems to trigger proper profile

**Pull request merged**
